import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";
import { Grid, Button, Box, Container, Typography } from "@mui/material";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  return (
    <>
      <Head>
        <title>Hacklahoma 23</title>
        <meta
          name="description"
          content="Generated by Thomas Nguyen and Tiffany Le"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user && (
        <Grid
          container
          spacing={0}
          direction="column"
          alignItems="center"
          justifyContent="center"
        >
          <Box sx={{ p: 4 }}>
            <Typography variant="h1" color="secondary">
              Hacklahoma 2023
            </Typography>
          </Box>
          <Link href="/game">
            <Button variant="contained">Start Game</Button>
          </Link>
        </Grid>
      )}

      {!user && (
        <Grid
          container
          spacing={0}
          direction="column"
          alignItems="center"
          justifyContent="center"
        >
          <Box
            sx={{
              p: 25,
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              textAlign: "center",
            }}
          >
            <Typography align="center" variant="h1" color="secondary">
              Hacklahoma 2023
            </Typography>

            <Typography align="center" variant="h3" color="secondary" sx={{mt: 3}}>
              The Hack Strikes Back: Gambling
            </Typography>

            <Typography
              align="center"
              variant="h5"
              color="secondary"
              width={400}
              sx={{ mx: "auto", mt: 3 }}
            >
              Inspired by the Vietnamese gambling game, Bầu Cua Tôm Cá. Help
              Luke and his friends earn enough tokens to fight against the
              empire by competitive betting!
            </Typography>
          </Box>
        </Grid>
      )}
    </>
  );
}
